# Generated by Django 3.2.4 on 2021-06-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techform',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='techform',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='techform',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
